### ISSUE TITLE
building error: 'blitz/array.h' file not found

### ISSUE THREAD

**Issue by porres** [grrrr/constantq#2]
(comment was edited)

so, here's the deal... I have the dependencies right (blitz++ / FFTW3 & flext) and tried building it by going to the constanq folder on the terminal and typing "bash ../flext/build.sh pd gcc" - the flext folder is correctly located in that path. And here's what I get as the error: 

-------------------------------------

In file included from main.cpp:27:
./headers/constantq.hpp:8:10: fatal error: 'blitz/array.h' file not found
#include <blitz/array.h>

**Comment by porres** [comment]
I see it's not finding the flext.h file, but where and how should I fix that? thanks

**Comment by porres** [comment]
oops, seems I hadn't really installed flext, trying again...

**Comment by porres** [comment]
yeah, now I get a new error :) 

In file included from main.cpp:27:
./headers/constantq.hpp:8:10: fatal error: 'blitz/array.h' file not found
#include <blitz/array.h>

**Comment by porres** [comment]
but I got 'blitz/array.h' alright, here it is, in "usr/local/include/blitz/array.h"

<img width="523" alt="screen shot 2017-05-09 at 22 53 13" src="https://cloud.githubusercontent.com/assets/5360142/25879859/51b6dd38-350a-11e7-9442-4ef6a570bfa1.png">

**Comment by grrrr** [comment]
Would you please try to compile with the following command line:
CFLAGS="-I /usr/local/include" ../flext/build.sh pd gcc

**Comment by porres** [comment]
well, this is what I got :) 
<img width="625" alt="screen shot 2017-05-10 at 11 16 01" src="https://cloud.githubusercontent.com/assets/5360142/25903190/1af3ec74-3572-11e7-8e05-3fe1c9e8b7ca.png">

**Comment by porres** [comment]
so, do I always need to use this flag (CFLAGS="-I /usr/local/include")? Where is it documented?

thanks

**Comment by grrrr** [comment]
It seems kind of unusual for a compiler to not recognize this system path by default. I have no idea why/how this can happen. You can add the flags to your flext config file flext/buildsys/config-*.txt, matching with your platform, e.g. with the UFLAGS variable.
