### ISSUE TITLE
issue building again

### ISSUE THREAD

**Issue by porres** [grrrr/constantq#4]
hey, me again, so... I did format my mac, now that I tried again, I have a new issue. Don't know what could be wrong, cause I did the same thing as before.

seems it is not finding "-lfftw3f"

here's the error
<img width="843" alt="screen shot 2017-06-13 at 20 30 48" src="https://user-images.githubusercontent.com/5360142/27109192-af51d7d0-5077-11e7-9c2c-e8a36537402a.png">

here's FFTW3 on my computer, this is all I see, no  -lfftw3f is here indeed
<img width="843" alt="screen shot 2017-06-13 at 20 30 48" src="https://user-images.githubusercontent.com/5360142/27109213-c54d2efe-5077-11e7-9df1-e71dd44119bc.png">

btw, me and @esantossilva are trying to build and use this in an android studio app, we can provide contantq~ a compiled version for windows so it is available in deken

cheers

**Comment by porres** [comment]
so, followed an advise here https://github.com/pyFFTW/pyFFTW/issues/70

"The only way to get all three different FFTW datatypes required for pyfftw is to do

$ ./configure --enable-threads --enable-shared
$ make
$ sudo make install
$ ./configure --enable-threads --enable-shared --enable-float
$ make
$ sudo make install
$ ./configure --enable-threads --enable-shared --enable-long-double
$ make
$ sudo make install"

now I get a new error

**"ld: warning: ignoring file /usr/local/lib/libfftw3f.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libfftw3f.dylib"

strip -x pd-darwin/release-single/constantq~.pd_darwin

chmod 755 pd-darwin/release-single/constantq~.pd_darwin

Alexandres-MacBook-Pro:constantq porres$**

**Comment by grrrr** [comment]
Hi, not exactly a constantq~ issue. For 32-bit Pd you need to build the fftw3f library in 32-bit (or better, combined 32/64-bit) mode. You could also use a 64-bit Pd and build everything in 64 bits.

**Comment by porres** [comment]
in building flext, I chose Pd 64 bits for its m_pd.h. So this means I built fftw in 32 and there is a conflict, right? Best option seems to build it for combined 32/64-bit, but I don't remember doing anything differently before to achieve that. Would you have any hints? Thanks
